version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./.env
    # network_mode: "host"        
    restart: unless-stopped
    # depends_on:
    #   - db
  # db:
  #   # network_mode: "host"        
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=notices
  #     - POSTGRES_PASSWORD=notices
  #     - POSTGRES_DB=notices
  #   restart: always

# volumes:
#   postgres_data: